const homeRouter = require("./home.router");
const clientRouter = require("./userClient.router");
const categoryRouter = require("./category.router");
const productRouter = require("./product.router");
const productClientRouter = require("./productClient.router");
const cartRouter = require("./cart.router");
const myListRouter = require("./myList.router");
const addressRouter = require("./address.router");
const adminUser = require("./userAdmin.router");
const bannerHome = require("./bannerHome.router");
const bannerList = require("./bannerList.router");
const blogRouter = require("./blog.router");
const logoRouter = require("./logo.router");
const roleRouter = require("./role.router");
const authRouter = require("./auth.router");
const checkoutRouter = require("./checkout.router");
const orderRouter = require("./order.router");
const orderAdminRouter = require("./orderAdmin.router");
const reviewProductRouter = require("./reviewProduct.router");
const notifyRouter = require("./notification.router");
module.exports = (app) => {
  app.use("/api/dashboard", homeRouter);
  app.use("/api/user", clientRouter);
  app.use("/api/category", categoryRouter);
  app.use("/api/product", productRouter);
  app.use("/api/productClient", productClientRouter);
  app.use("/api/reviewProduct", reviewProductRouter);
  app.use("/api/cart", cartRouter);
  app.use("/api/myList", myListRouter);
  app.use("/api/address", addressRouter);
  app.use("/api/userAdmin", adminUser);
  app.use("/api/banner", bannerHome);
  app.use("/api/bannerList", bannerList);
  app.use("/api/blog", blogRouter);
  app.use("/api/logo", logoRouter);
  app.use("/api/role", roleRouter);
  app.use("/auth", authRouter);
  app.use("/api/checkout", checkoutRouter);
  app.use("/api/order", orderRouter);
  app.use("/api/orderAdmin", orderAdminRouter);
  app.use("/api/notification", notifyRouter);
};
